### ISSUE TITLE
1st house editions

### ISSUE THREAD

**Issue by iillyyaa2033** [iillyyaa2033/nmud-content#3]
Список того, что надо бы сделать:
- [x] Дождаться, когда я прикручу к тэгам автосоздание полей;
- [x] Навесить тэги на двери;
- [ ] Насесить тэги на стены
- [x] Проверить возможность переходов между всеми комнатами на сервере

**Comment by iillyyaa2033** [comment]
@klessh, призываю тебя в этот issue! Кстати, добавил недостающие тэги дверей (efd961a), тебе стоит обновиться.

**Comment by klessh** [comment]
Какие тэги для стен? Не понял... Возможность проверю, когда починишь Ктулху.

**Comment by iillyyaa2033** [comment]
@klessh, забудь про стены. Закрываю исью.
